name: smart_aalna
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  flutter_dotenv: ^6.0.0
  image_background_remover: ^2.0.0
  flutter_colorpicker: ^1.1.0
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  http: ^1.6.0
  shimmer_animation: ^2.2.2+1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
